name: monocular_tac
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.8
  - pytorch=2.4.1
  - pytorch-cuda=12.1
  - torchvision=0.20.0
  - torchaudio=2.4.1
  - pip
  - pip:
      - numpy==1.24.4
      - matplotlib==3.7.5
      - pillow==10.4.0
      - opencv-python==4.12.0.86
      - pyyaml
      - tqdm==4.67.1
      - open3d==0.19.0
      - scipy==1.10.1
      - scikit-image==0.21.0
      - timm
      - tensorboardx==2.6.2.2
      - tqdm==4.67.1
