name: monocular_tac
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.3.7=py38h9128911_0
  - brotli-python=1.0.9=py38hd77b12b_8
  - ca-certificates=2025.12.2=haa95532_0
  - colorama=0.4.6=py38haa95532_0
  - cuda-cccl=12.9.27=0
  - cuda-cccl_win-64=12.9.27=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-opencl-dev=12.9.19=0
  - cuda-profiler-api=12.9.79=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - flask=3.0.3=py38haa95532_0
  - freetype=2.13.3=h0620614_0
  - giflib=5.2.2=h7edc060_0
  - gmpy2=2.1.2=py38h7f96b67_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - itsdangerous=2.2.0=py38haa95532_0
  - jpeg=9f=ha349fce_0
  - khronos-opencl-icd-loader=2024.05.08=h8cc25b3_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.3.10.19=0
  - libcurand-dev=10.3.10.19=0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libpng=1.6.50=h46444df_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h3d04722_1
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py38h2bbff1b_1
  - mkl_fft=1.3.8=py38h2bbff1b_0
  - mkl_random=1.2.4=py38h59b6b97_0
  - mpc=1.1.0=h7edee0f_1
  - mpfr=4.0.2=h62dcd97_1
  - mpir=3.0.0=hec2e145_1
  - mpmath=1.3.0=py38haa95532_0
  - networkx=3.1=py38haa95532_0
  - numexpr=2.8.4=py38h7b80656_1
  - numpy-base=1.24.3=py38h8a87ada_1
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.19=hbb43b14_0
  - pandas=2.0.3=py38h4ed8f06_0
  - pillow=10.4.0=py38h827c3e9_0
  - pip=24.2=py38haa95532_0
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.20=h8205438_0
  - python-dateutil=2.9.0post0=py38haa95532_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytorch=2.4.1=py3.8_cuda12.1_cudnn9_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py38haa95532_0
  - setuptools=75.1.0=py38haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - sympy=1.13.3=py38haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - typing_extensions=4.11.0=py38haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.2.3=py38haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.44.0=py38haa95532_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zipp=3.20.2=py38haa95532_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - asttokens==3.0.0
      - attrs==25.3.0
      - backcall==0.2.0
      - blinker==1.8.2
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.1.8
      - comm==0.2.3
      - configargparse==1.7.1
      - contourpy==1.1.1
      - cycler==0.12.1
      - dash==3.2.0
      - decorator==5.2.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.16.1
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - ipython==8.12.3
      - ipywidgets==8.1.7
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-core==5.8.1
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - narwhals==1.42.1
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - numpy==1.24.4
      - open3d==0.19.0
      - opencv-python==4.12.0.88
      - packaging==25.0
      - parso==0.8.5
      - pickleshare==0.7.5
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - plotly==6.3.1
      - prompt-toolkit==3.0.52
      - protobuf==5.29.5
      - pure-eval==0.2.3
      - pycocotools==2.0.7
      - pygments==2.19.2
      - pyparsing==3.1.4
      - pywavelets==1.4.1
      - pywin32==311
      - pyyaml==6.0.3
      - referencing==0.35.1
      - requests==2.32.4
      - retrying==1.4.2
      - rpds-py==0.20.1
      - safetensors==0.5.3
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - shapely==2.0.7
      - six==1.17.0
      - stack-data==0.6.3
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - timm==1.0.21
      - torchaudio==2.4.1
      - torchvision==0.20.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.13.2
      - wcwidth==0.2.14
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.14
prefix: C:\Users\chenxin\anaconda3\envs\monocular_tac
